server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca0okwo8st6n.ap-northeast-2.rds.amazonaws.com:3306/back-20220829
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

servlet:
  multipart: #파일 저장시 필요. 용량제한
    max-file-size: 100MB
    max-request-size: 100MB 
    
file: #파일 저장 경로 #@Value("${file.path}")로 사용한다.
  path: C:/Korea IT/web/springboot/springboot-mybatis-20220923-youri/upload/


